# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

services:
  web:
    build: ./epaper_converter
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./epaper_converter/:/usr/src/epaper_converter/
    ports:
      - 8321:8000
    env_file:
      - ./.env.dev