# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

services:
  web:
    build: ./epaper_converter
    command: gunicorn epaper_converter.wsgi --bind 0.0.0.0:8000 --workers 5
    volumes:
      - ./epaper_converter/:/usr/src/epaper_converter/
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - ./static_root/:/usr/share/nginx/static_root/
      - ./epaper_converter/media/:/usr/share/nginx/media/
    ports:
      - 1337:80
    depends_on:
      - web