# Generated by Django 5.0 on 2024-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('converted_image', models.ImageField(blank=True, null=True, upload_to='images/converted/')),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=448)),
                ('height', models.FloatField(default=600)),
                ('rotation', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
