# Generated by Django 5.0 on 2023-12-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='original_image',
        ),
        migrations.AddField(
            model_name='image',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
