# Generated by Django 5.0 on 2023-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_image_image_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.FloatField(default=600),
        ),
        migrations.AddField(
            model_name='image',
            name='offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.FloatField(default=448),
        ),
        migrations.AlterField(
            model_name='image',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/converted/'),
        ),
    ]
