# Generated by Django 5.0 on 2024-02-18 13:08

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.upload_to_thumbs),
        ),
        migrations.AlterField(
            model_name='image',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.upload_to_converted),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to=images.models.upload_to),
        ),
    ]
