# Generated by Django 5.0 on 2023-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
